#define menu_IR "Controle IR"
#define menu_tempo "Tempo"
#define menu_teclado "Teclado"
#define menu_configuracao "Configuracao"
#define config_tema "Tema"
#define config_tema_padrao "Padrao"
#define tempo_hora "Hora"
#define tempo_data "Data"
#define tempo_brilho "Brilho"